# Generated by Django 5.2.7 on 2025-10-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_address_country_remove_address_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='+201000000000', max_length=13),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('phone_number__regex', '^\\+201[0-9]{9}$'), ('phone_number__regex', '^01[0-9]{9}$'), _connector='OR')), name='valid_egyptian_phone_number'),
        ),
    ]
