# Generated by Django 5.2.7 on 2025-10-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name_plural': 'Addresses'},
        ),
    ]
