# Generated by Django 5.2.7 on 2025-10-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-updated_at'], 'verbose_name_plural': 'Addresses'},
        ),
    ]
