# Generated by Django on 2025-11-30

from django.db import migrations


CREATE_FUNCTIONS_SQL = r"""
-- Function: prevent setting cart to checked_out when items exist
CREATE OR REPLACE FUNCTION carts_prevent_checkout_with_items()
RETURNS trigger AS $$
BEGIN
    IF NEW.status = 'checked_out' THEN
        IF EXISTS (
            SELECT 1 FROM carts_cartitem i WHERE i.cart_id = NEW.id
        ) THEN
            RAISE EXCEPTION 'Cannot set cart % to checked_out while it still has items', NEW.id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- Function: prevent adding items to a cart already checked_out
CREATE OR REPLACE FUNCTION carts_prevent_items_into_checked_out_cart()
RETURNS trigger AS $$
DECLARE
    _status text;
BEGIN
    SELECT status INTO _status FROM carts_cart WHERE id = NEW.cart_id FOR SHARE;
    IF _status = 'checked_out' THEN
        RAISE EXCEPTION 'Cannot add or modify items for a checked out cart %', NEW.cart_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


CREATE_TRIGGERS_SQL = r"""
-- Trigger on carts_cart BEFORE UPDATE
DROP TRIGGER IF EXISTS trg_carts_prevent_checkout_with_items ON carts_cart;
CREATE TRIGGER trg_carts_prevent_checkout_with_items
BEFORE UPDATE ON carts_cart
FOR EACH ROW
EXECUTE FUNCTION carts_prevent_checkout_with_items();

-- Trigger on carts_cartitem BEFORE INSERT OR UPDATE
DROP TRIGGER IF EXISTS trg_carts_prevent_items_into_checked_out_cart ON carts_cartitem;
CREATE TRIGGER trg_carts_prevent_items_into_checked_out_cart
BEFORE INSERT OR UPDATE ON carts_cartitem
FOR EACH ROW
EXECUTE FUNCTION carts_prevent_items_into_checked_out_cart();
"""


DROP_TRIGGERS_SQL = r"""
DROP TRIGGER IF EXISTS trg_carts_prevent_items_into_checked_out_cart ON carts_cartitem;
DROP TRIGGER IF EXISTS trg_carts_prevent_checkout_with_items ON carts_cart;
"""


DROP_FUNCTIONS_SQL = r"""
DROP FUNCTION IF EXISTS carts_prevent_items_into_checked_out_cart();
DROP FUNCTION IF EXISTS carts_prevent_checkout_with_items();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cart_items_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_FUNCTIONS_SQL + CREATE_TRIGGERS_SQL,
            reverse_sql=DROP_TRIGGERS_SQL + DROP_FUNCTIONS_SQL,
        ),
    ]
