# Generated by Django 5.2 on 2025-09-24 07:17

import catalog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_image_url_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.utils.product_cover_file_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=280, unique=True),
        ),
    ]
