# Generated by Django 5.2.7 on 2025-12-05 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_orderitem_product'),
        ('users', '0005_alter_address_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['delivered', 'canceled']), ('address__isnull', False), _connector='OR'), name='address_nullable_only_when_delivered_or_canceled'),
        ),
    ]
